### ISSUE TITLE
IOS No Video Until Page is Restored

### ISSUE THREAD

**Issue by r00tk1ll** [nimiq/qr-scanner#125]
Using the latest version of IOs on an ipad I can not get the video to display until either the browser is minimized and restored, navigating to a new tab and back to the original page or locking the screen then unlocking it.

Is there a workaround for this issue?

**Comment by Yukiioz** [comment]
Hi @r00tk1ll , we're looking into this issue but unfortunately we cannot properly test / debug it without a real device. We'll update the github issue as soon as we get our hands on one. Please share as much details as possible to make it easier for us to reproduce. (iOS version, browser, etc...)

**Comment by ablagoev** [comment]
Hey all,

This seems to be a known bug in Webkit from 2017:

https://bugs.webkit.org/show_bug.cgi?id=179363

As in the title, calling `getUserMedia()` after the stream has already been started (i.e. after `scanner.start()`) blocks the initial stream.

Using QrScanner.listCameras(true) triggers the call to getUserMedia. If you don't need the labels you can just use QrScanner.listCameras() and the stream will not stop.

Alternatively, you can switch the order of operations as in the comment from the example. Something like this:

```js
QrScanner.listCameras(true)
    .then(function() {
         scanner.start()
    });
```

Another option that is working would be to pause the video and start it again after 300ms, something like this:

```js
scanner.pause();
setTimeout(function() {
    scanner.start();
}, 300);
```

Be careful, as it won't work with a timeout below 300 ms., because apparently there is a delay for video.pause().

There might be workarounds which can be added in the library, so this all gets handled under iOS, but I am not sure if it is worth the effort.

**Comment by danimoh** [comment]
This is fixed now.
As @ablagoev figured out (thanks!) this issue showed when calling `QrScanner.listCameras(true)` *after* the scanner was started.
