### ISSUE TITLE
turnFlashOn throws an error

### ISSUE THREAD

**Issue by pstanton** [nimiq/qr-scanner#126]
qr-scanner@^1.3.0:
  version "1.3.0"

> Uncaught (in promise) ReferenceError: e is not defined

 ```
   turnFlashOn() {
        if (this._flashOn) return Promise.resolve();
        this._flashOn = true;
        if (!this._active || this._paused) return Promise.resolve(); // flash will be turned on later on .start()
        return this.hasFlash().then((hasFlash) => {
            if (!hasFlash) return Promise.reject('No flash available');
            // Note that the video track is guaranteed to exist at this point
            return this.$video.srcObject.getVideoTracks()[0].applyConstraints({
                advanced: [{ torch: true }],
            });
        }).catch(() => {
            this._flashOn = false;
            throw e;
        });
    }
```

My guess is that `        }).catch(() => {` should be `        }).catch(e => {`

**Comment by danimoh** [comment]
Thanks!
The newest release does now correctly rethrow the exception.
Luckily, `throw e` was throwing nonetheless, just with an `Uncaught ReferenceError` instead of the correct exception :smile:.
The whole library is now also written in typescript which should help prevent such issues in the future :)
