### ISSUE TITLE
How can i make the reader full width ?

### ISSUE THREAD

**Issue by techyroots** [nimiq/qr-scanner#54]
Hi there, 

I am using this scanner script to scan the QR code on mobile devices through the browser. But the problem is the reader is not 100% full width or how I can change the scanning angle of the screen?

**Comment by danimoh** [comment]
Hello.
For image scanning via `scanImage()` the full image is used by default.
For webcam scanning, a square of two thirds of the video's width or height, whichever is smaller, is used.
This is hard coded but if you want to change it, you can do so by overwriting `_updateSourceRect` before starting to scan.
Note that the source rect should still be a square. Otherwise set the `$canvas.width` and `$canvas.height` accordingly.

**Comment by danimoh** [comment]
Using a custom scan are is now supported.

**Comment by MarufSharifi** [comment]
Hi, thanks for doing this great job, 

I want to make the width to be full and height to be a specific percent of height of screen, 

### current behavior: 

when i change the height the width automatically changes base on height and width can't be full.

### expected behavior: 

when i set the width and height they take place accordingly
