### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' 

### ISSUE THREAD

**Issue by AKclown** [nimiq/qr-scanner#70]
qr-scanner-worker.min.js:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by mikeychowy** [comment]
did you rewrite the worker? i seem to bundled the initial files well enough.

**Comment by danimoh** [comment]
Hello.
To me this sounds like the worker was not found at the specified `WORKER_PATH` and your server was configured to serve a fallback html file instead of the missing file which can not be parsed as javascript.
Can you investigate in the network tab of the dev tools what file you got served instead of the worker?
Note that the `WORKER_PATH` needs to be set before creating the `QrScanner` instance.

For Webpack users, the Readme now includes extended setup instructions.

**Comment by alexmarincas** [comment]
Hello, in my case, the solution was to copy qr-scanner-worker.min.js and qr-scanner-worker.min.js.map in the public folder (I've placed the files in a folder called qr-scanner). Then, inside my component I've imported QRScanner ( import QRScanner from 'qr-scanner' ) and then I've set QRScanner.WORKER_PATH = "qr-scanner/qr-scanner-worker.min.js"

**Comment by danimoh** [comment]
For anyone running into the same issue: please have a look at the readme.

**Comment by famingyuan** [comment]
stupid op

**Comment by danimoh** [comment]
@famingyuan not sure what you're hinting at.
`op` could for example mean "original poster", i.e. AKClown, or "operator", i.e. me?
If you feel the urge to insult people, at least be clear about who you mean.
In any case, insulting people is not nice.
If you have anything meaningful to contribute, e.g. by asking a proper question or improving the readme, please do.

**Comment by chainrocker55** [comment]
qr-scanner-worker.min.js:1 Uncaught SyntaxError: Unexpected token '<' I already use a worker path but it can not scan perfectly and I see it doesn't support windows os, I try to use windows os on the demo https://nimiq.github.io/qr-scanner/demo/?fbclid=IwAR04ncPlvbx4HwwM76BIfwpAL6LbU3HIscCx1-FyIrT-jLLPlvDGVoee59Y here but also not working

**Comment by danimoh** [comment]
The api has been simplified and setting the `WORKER_PATH` is now not required anymore :)
