### ISSUE TITLE
Select from multiple back-cameras

### ISSUE THREAD

**Issue by adrha** [nimiq/qr-scanner#83]
I want to select which camera is used for the scanning.

My problem:
On modern mobile-phones you have multiple cameras mounted.
On Huawei P30 for example the lib takes the "tele"-camera which needs a big distance between code and phone.

On the Desktop, i want to be able to scan with a connected USB-Cam so i need to be able to select which cam is used.

How can this be done?

Can anyone help me?

**Comment by glenngartner** [comment]
It's been a while since you posted this, and may no longer require the answer, but you can set the desired camera using the native navigator.mediaDevices call. You don't require this library to select any device you have available on your hardware. I've successfully toggled between 3 webcams on a PC, and 4 cameras on a mobile device. 
 navigator.mediaDevices.enumerateDevices() returns a promise with a list of devices on the host hardware. From that, construct a list of available media devices. When you have the desired camera from that list, store it's id, and set the desired camera using navigator.mediaDevices.getUserMedia(<your media device with unique id>), and set the src object on your video element to the media stream that method returns in it's Promise. 
Sounds confusing? Perhaps, if you're new to media devices. It's quite simple. If you or someone else wants a little hand holding, just reply, and I'll elaborate. For those experienced w/ navigator and media devices, that above should get you started in the right direction.

**Comment by danimoh** [comment]
Hello there,
the latest version of this lib now supports choosing a camera :)
