### ISSUE TITLE
define scan frame rate

### ISSUE THREAD

**Issue by poolerMF** [nimiq/qr-scanner#93]
user can specify custom scan region, so picture for scanning can be bigger

funciton _scanFrame - there should be something like "counter" and setting **scanFrameRatio** 
scanImage will be called every x-th times

if **scanFrameRatio** = 2, every second animation frame will scan image

````
_scanFrame() {
    ....

    requestAnimationFrame(() => {
        this.counter++;
        if(this.counter % this.scanFrameRatio === 0) {
            QrScanner.scanImage ...
        }
    });
}

**Comment by danimoh** [comment]
Hello @poolerMF,
nice feature suggestion.
I hope to find time to work on this in the near future.

**Comment by danimoh** [comment]
Scan rate throttling is now supported.
However, instead of a fixed frame skipping rate, I decided to base it on the scanned frames per second.
The default is 25 scanned frames per second, which should be enough as higher rates drain the battery faster.
This value can be configured though, of course.
On browsers that support it, the scan rate is never higher than the camera's frame rate to avoid duplicate scans on the same frame.
